apiVersion: v1
kind: Service
metadata:
  name: external-nginx-service
  namespace: wh-ns
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: 'true'
spec:
  selector:
    name: deploy-hpa
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
