---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pdb
  namespace: wh-ns
rules:
- apiGroups: ["*"]
  resources: ["deployments", "configmaps", "pods", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pdb
  namespace: wh-ns
subjects:
- kind: Group
  name: pdb
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: pdb
  apiGroup: rbac.authorization.k8s.io
