apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<aws-account-id>:role/eks-admin-role
      username: eks-admin-role
      groups:
      - system:masters
    - rolearn: arn:aws:iam::<aws-account-id>:role/<cluster-name>-worker
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::<aws-account-id>:user/developer
      username: pdb
      groups:
        - pdb
